"""added task category

Revision ID: 07e65a5209ca
Revises: 87f205872f92
Create Date: 2026-02-19 10:27:08.977161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e65a5209ca'
down_revision: Union[str, Sequence[str], None] = '87f205872f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    task_category_enum = sa.Enum('WORK', 'PERSONAL', 'STUDY', 'OTHER', name='taskcategory')
    task_category_enum.create(op.get_bind())
    op.add_column('tasks', sa.Column('category', task_category_enum, nullable=False, server_default='OTHER'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'category')

    task_category_enum = sa.Enum('WORK', 'PERSONAL', 'STUDY', 'OTHER', name='taskcategory')
    task_category_enum.drop(op.get_bind())
    # ### end Alembic commands ###
